### ISSUE TITLE
Checklist for 0.17.0

### ISSUE THREAD

**Issue by hammertater** [hammertater/treechop#140]
New stuff:
- [x] (Forge 1.19) Restore Jade & WTHIT support
- [x] Add The One Probe support
- [x] Better configuration for tree blocks and chopping tools
- [x] Many API additions
- [x] Fix spillover chops not getting visualized
- [x] Fix textures for chopped mushroom stems
- [x] Fix textures for bark removal on mismatched blocks
- [x] Fix chop detector appearing for spectators
- [x] Fix client-side rendering-related crashes due to mod conflicts
- [x] Fix WTHIT widget for trees with multiple log types
- [x] Stop bamboo from being choppable when using William Wythers' Overhauled Overworld 
- [x] Fix conflicts with TerraformersMC mods
- [x] Fix chopping XP awards for Project MMO

Testing:
- [x] Blacklist items
- [x] Whitelist items

**Comment by hammertater** [comment]
Released
